name: Publish Snapshot package to the Maven Central Repository

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Write gradle.properties
        run: |
          mkdir -p ~/.gradle
          cat << EOF > ~/.gradle/gradle.properties
          sonatypeUsername=${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          sonatypePassword=${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          signingInMemoryKey=${{ secrets.GPG_PRIVATE_KEY }}
          signingInMemoryKeyId=${{ secrets.GPG_KEY_ID }}
          signingInMemoryKeyPassword=${{ secrets.GPG_PASSPHRASE }}
          EOF
          # Also create in project directory to ensure it's found
          cat << EOF > java/keypop-gradle/gradle.properties
          sonatypeUsername=${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          sonatypePassword=${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          signingInMemoryKey=${{ secrets.GPG_PRIVATE_KEY }}
          signingInMemoryKeyId=${{ secrets.GPG_KEY_ID }}
          signingInMemoryKeyPassword=${{ secrets.GPG_PASSPHRASE }}
          EOF

      - name: Setup GPG (not needed for in-memory signing)
        run: echo "Using in-memory GPG signing"

      - name: Update permissions
        run: chmod +x ./gradlew
        working-directory: java/keypop-gradle

      - name: Build and Publish Snapshot
        run: ./gradlew build test publish --info --stacktrace
        working-directory: java/keypop-gradle