name: Publish Snapshot package to the Maven Central Repository

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Write gradle.properties
        run: |
          mkdir -p ~/.gradle
          cat << EOF > ~/.gradle/gradle.properties
          signing.keyId=${{ secrets.GPG_KEY_ID }}
          signing.password=${{ secrets.GPG_PASSPHRASE }}
          signing.secretKeyRingFile=\$HOME/.gradle/maven-central.gpg
          sonatypeUsername=${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          sonatypePassword=${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          EOF

      - name: Install gpg secret key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --export-secret-keys > ~/.gradle/maven-central.gpg

      - name: Update permissions
        run: chmod +x ./gradlew

      - name: Build and Publish Snapshot
        run: ./gradlew build test publish --info --stacktrace